apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-service
  template:
    metadata:
      labels:
        app: node-service
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: node-service
        image: 202403775442.dkr.ecr.ap-south-1.amazonaws.com/node-service:latest
        ports:
        - containerPort: 3000
